In [1]:
import pandas as pd

In [2]:
ipeds_df = pd.read_csv("ipeds_hd2024.csv")
scorecard_df = pd.read_csv("scorecard_raw.csv")

In [3]:
ipeds_df.isna().sum()

UNITID     0
INSTNM     0
CONTROL    0
LOCALE     0
dtype: int64

In [4]:
scorecard_df.isna().sum()

id                                                0
school.name                                       0
latest.cost.tuition.in_state                   2660
latest.cost.tuition.out_of_state               2660
latest.earnings.10_yrs_after_entry.median      1149
latest.aid.median_debt.completers.overall      1507
latest.completion.rate_suppressed.four_year    4156
latest.student.size                             735
dtype: int64

In [5]:
cleaned_sc = scorecard_df.dropna(axis=0)
cleaned_sc.describe()

,id,latest.cost.tuition.in_state,latest.cost.tuition.out_of_state,latest.earnings.10_yrs_after_entry.median,latest.aid.median_debt.completers.overall,latest.completion.rate_suppressed.four_year,latest.student.size
count,1905.000000,1905.000000,1905.000000,1905.000000,1905.000000,1905.000000,1905.000000
mean,201772.566404,24898.617323,29217.862467,53444.377953,21270.180052,0.527590,5369.110761
std,79327.938349,18541.414382,16412.965633,15653.840136,5998.023566,0.189596,9652.443910
min,100654.000000,895.000000,895.000000,19474.000000,2959.000000,0.000000,2.000000
25%,154004.000000,9387.000000,16579.000000,43166.000000,18500.000000,0.389000,942.000000
50%,192703.000000,18075.000000,25754.000000,51673.000000,22500.000000,0.527200,2076.000000
75%,220631.000000,38050.000000,39824.000000,60823.000000,25375.000000,0.663400,5612.000000
max,498571.000000,72097.000000,72097.000000,143372.000000,43021.000000,0.974500,163164.000000

In [6]:
scorecard_df.describe()

,id,latest.cost.tuition.in_state,latest.cost.tuition.out_of_state,latest.earnings.10_yrs_after_entry.median,latest.aid.median_debt.completers.overall,latest.completion.rate_suppressed.four_year,latest.student.size
count,6.322000e+03,3662.000000,3662.000000,5173.000000,4815.000000,2166.000000,5587.000000
mean,2.217185e+06,17753.961496,21231.100492,43700.300986,15806.127310,0.521117,2592.512977
std,7.742673e+06,16350.637495,15353.464437,17142.597031,7632.208102,0.196485,6472.212587
min,1.006540e+05,0.000000,0.000000,8579.000000,2783.000000,0.000000,0.000000
25%,1.742375e+05,5792.500000,9935.000000,31914.000000,9500.000000,0.376225,120.000000
50%,2.290225e+05,11943.500000,16364.000000,40747.000000,13432.000000,0.521900,540.000000
75%,4.589105e+05,23760.000000,28535.000000,52341.000000,22500.000000,0.663300,2163.000000
max,4.966450e+07,72097.000000,72097.000000,143372.000000,43021.000000,1.000000,163164.000000

In [7]:
cleaner_sc = cleaned_sc[cleaned_sc["latest.student.size"] > 50]
cleaner_sc.describe()

,id,latest.cost.tuition.in_state,latest.cost.tuition.out_of_state,latest.earnings.10_yrs_after_entry.median,latest.aid.median_debt.completers.overall,latest.completion.rate_suppressed.four_year,latest.student.size
count,1897.000000,1897.000000,1897.000000,1897.000000,1897.000000,1897.000000,1897.000000
mean,201431.476542,24885.140221,29222.600422,53508.214549,21266.101212,0.527701,5391.648919
std,78882.187893,18549.823288,16414.059374,15644.344411,5989.686288,0.189572,9666.528300
min,100654.000000,895.000000,895.000000,19474.000000,2959.000000,0.000000,52.000000
25%,153977.000000,9303.000000,16600.000000,43177.000000,18500.000000,0.391300,954.000000
50%,192448.000000,18075.000000,25754.000000,51724.000000,22500.000000,0.527200,2087.000000
75%,220604.000000,38004.000000,39822.000000,60909.000000,25375.000000,0.663400,5616.000000
max,498571.000000,72097.000000,72097.000000,143372.000000,43021.000000,0.974500,163164.000000

In [8]:
cleaner_sc.to_csv("scorecard_cleaned.csv")